### ISSUE TITLE
I needs something to tell me if the cheat is working

### ISSUE THREAD

**Issue by Hacker1254** [Bea-E-Nutter/GimkitCheat#5]

**Comment by Bea-E-Nutter** [comment]
I agree, it takes some learning curve to use and the ReadMe file isn't very clear. I think it is worthy to note that it will not search online for the answer. You have to input the correct answer at least once per question for it to memorize it.

 I have it set up currently where you

- open up Gimit Live and log in and everything
- on the screen where you begin to answer questions, run the code either by entering the code script.js into the console or by opening the bookmarklet
- Press escape to use the cheat (This has to be done EVERY time a new question appears)

The first time you press escape, two boxes in the top bar to the far left of your balance should appear. Pressing "save" downloads a file that contains the data that stores the answers to the questions you have answered. You can also click the  "Choose File" button to select a file and load this data next time you play. 

Questions will not be answered for you, the answers in multiple-choice questions will change color depending on if they are right (green), wrong (red), or if the program does not know (grey). 

Also for text response questions, if the answer is known then it will be copied to your clipboard and can be pasted with control+V. Instead of the submit button saying "submit", it will be changed to the answer. If it does not know, the submit button will turn grey.

**Comment by Bea-E-Nutter** [comment]
If you desire to work on this, just let me know. The code is rushed and uncommented, but I am not really working on this anymore so I am welcome to bring someone else on board!

**Comment by Hacker1254** [comment]
Thank you!
